import * as React from 'react'
import Form from '@/components/Form'
import Head from 'next/head'
import icon from '../assets/images/icon-arrow.svg'
import { store } from '../store/store'
import { Provider } from 'react-redux'


export default function Home() {
	const [day, setDay] = React.useState('')
	const [month, setMonth] = React.useState('')
	const [year, setYear] = React.useState('')

	return (
		<>
			<Head>
				<title>Age calculator</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='mx-auto w-[90%]'>
				<section className='mt-3 h-[500px]'>
					<Form
						day={day}
						setDay={setDay}
						month={month}
						setMonth={setMonth}
						year={year}
						setYear={setYear}
					/>
					<div className='before:block before:my-20 before:h-[1px] before:w-full before:bg-gray-300 before:mx-auto'>
					</div>
					{/* <div className='bg-black'>
						<svg className='w-12 h-12 text-white ' src={icon} />
					</div> */}

				</section>
			</main>
		</>
	)
}
