import Form from '@/components/Form'
import Head from 'next/head'


export default function Home() {
	return (
		<>
			<Head>
				<title>Age calculator</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='mx-auto w-[90%]'>
				<section className='mt-3 h-[500px]'>
					<Form />
					<div className='before:block before:my-20 before:h-[1px] before:w-full before:bg-gray-300 before:mx-auto'>

					</div>
				</section>
			</main>
		</>
	)
}
