import * as React from 'react'
import Form from '@/components/Form'
import Head from 'next/head'
import icon from '../assets/images/icon-arrow.svg'
import { store } from '../store/store'
import { Provider } from 'react-redux'


export default function Home() {
	const [day, setDay] = React.useState('')
	const [month, setMonth] = React.useState('')
	const [year, setYear] = React.useState('')

	function calculateAge(birthDay) {
		let birthDate = new Date(birthDay)
		const today = new Date()

		// counting years between dates
		let age = today.getFullYear() - birthDate.getFullYear()

		// coutning months and days between dates
		let m = today.getMonth() - birthDate.getMonth()
		let d = today.getDate() - birthDate.getDate()

		// if current month is lower than birth month
		// or this month is equal to current month and current day
		// is lower than birth day
		if (m < 0 || (m === 0 && d < 0)) {
			age--;
			m += 12;
		}

		return { age, m, d }
	}

	function getBirthdayString() {
		return year + '-' + month + '-' + day
	}

	return (
		<>
			<Head>
				<title>Age calculator</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='mx-auto w-[90%]'>
				<section className='mt-3 h-[500px]'>
					<Form
						day={day}
						setDay={setDay}
						month={month}
						setMonth={setMonth}
						year={year}
						setYear={setYear}
					/>
					<div className='before:block before:my-20 before:h-[1px] before:w-full before:bg-gray-300 before:mx-auto'>
					</div>
					{/* <div className='bg-black'>
						<svg className='w-12 h-12 text-white ' src={icon} />
					</div> */}
					<p>{!year ? '-- ' : calculateAge(getBirthdayString()).age} years</p>
					<p>{!year ? '-- ' : calculateAge(getBirthdayString()).m} months</p>
					<p>{!year ? '-- ' : calculateAge(getBirthdayString()).d} days</p>
				</section>
			</main>
		</>
	)
}
